
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const CURRENT_USER = 'CURRENT_USER';
export const CURRENT_POST = 'CURRENT_POST';
export const ADD_COMMENT_TO_FAVORITES = 'ADD_COMMENT_TO_FAVORITES';
export const ADD_POST_TO_FAVORITES = 'ADD_POST_TO_FAVORITES';
export const DELETE_POST_FROM_FAVORITES = 'DELETE_POST_FROM_FAVORITES';
export const DELETE_COMMENT_FROM_FAVORITES = 'DELETE_COMMENT_FROM_FAVORITES';
