
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const CURRENT_USER = 'CURRENT_USER';